version: '3'

services:

  reverse-proxy:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.1
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    container_name: mysql
    image: "mysql:5.7"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - /Users/thomas/storage/mysql56-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    labels:
      - traefik.enable=false

  whoami:
    container_name: whoami
    # A container that exposes an API to show its IP address
    image: containous/whoami
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.test`)"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.test`)"
